component: scf
app: yangmaojb_py
name: yangmaojb_py
inputs:
  name: yangmaojb_py
  src: ./
  description: yangmaojb
  handler: index.main_handler
  runtime: Python3.6
  namespace: default
  region: ap-hongkong 
  memorySize: 64
  timeout: 333
  environment:
    variables:
      RUN_CONFIG: '{"xmly_speed":{"run":"false"}}'
  events:
    - timer:
        parameters:
          name: nocron
          cronExpression: "0 03,33 * * * * *"	
          enable: false
          argument: nocron?xmly_speed0&&xmly_speed1
    - timer:
        parameters:
          name: nocrontest
          cronExpression: "0 0/2 * * * * *"	
          enable: false
          argument: nocron?xmly_speed0&&xmly_speed1